import { StyleSheet } from 'react-native';
import { radii } from '@/src/constants/layout';
import type { AppTheme } from '@/src/hooks/use-theme';

export function createMapScreenStyles({ colors, fonts }: AppTheme) {
  return StyleSheet.create({
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    headerText: { flex: 1, gap: 2 },
    searchAreaBtn: {
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 40,
      borderRadius: radii.full,
      borderWidth: 1,
      borderColor: colors.accent,
      backgroundColor: colors.card,
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginTop: 4,
    },
    searchAreaText: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 13,
      fontWeight: '600',
      color: colors.accent,
    },
    legendTitle: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
      marginTop: 2,
    },
    legendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 14,
    },
    mapAttribution: {
      fontFamily: fonts.sans,
      fontSize: 11,
      color: colors.textMuted,
      lineHeight: 14,
    },
    mapLevelOverlay: {
      position: 'absolute',
      top: 8,
      right: 8,
      minHeight: 42,
      maxWidth: 200,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 8,
      borderWidth: 1.5,
      backgroundColor: colors.card,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    mapLevelDot: { width: 10, height: 10, borderRadius: 5 },
    mapLevelCopy: { flexShrink: 1, gap: 1 },
    mapLevelTaxon: {
      fontFamily: fonts.sans,
      fontSize: 10,
      color: colors.textMuted,
    },
    mapLevelText: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 13,
      color: colors.text,
    },
    heatmapEmptyOverlay: {
      position: 'absolute',
      left: 8,
      right: 8,
      bottom: 8,
      borderRadius: 8,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    heatmapEmptyText: {
      fontFamily: fonts.sans,
      fontSize: 12,
      lineHeight: 16,
      color: colors.textSecondary,
    },
    yandexBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: radii.full,
      borderWidth: 1,
      borderColor: colors.warningBorder,
      backgroundColor: colors.warningLight,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    yandexBannerText: {
      flex: 1,
      fontFamily: fonts.sans,
      fontSize: 12,
      color: colors.warningText,
      lineHeight: 16,
    },
    listFirstHint: {
      fontFamily: fonts.sans,
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 16,
    },
    tipCard: { gap: 10 },
    tipText: {
      fontFamily: fonts.sans,
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    calendarCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 14 },
    calendarBody: { flex: 1, gap: 4 },
    calendarTitle: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 15,
      color: colors.text,
    },
    calendarText: { fontFamily: fonts.sans, fontSize: 12, color: colors.textSecondary },
  });
}

export type MapScreenStyles = ReturnType<typeof createMapScreenStyles>;
