import { StyleSheet } from 'react-native';
import { radii } from '@/src/constants/layout';
import type { AppTheme } from '@/src/hooks/use-theme';

export function createCourseEditorStyles({ colors, fonts }: AppTheme) {
  return StyleSheet.create({
    section: { gap: 4, marginBottom: 12 },
    fieldGap: { marginTop: 12 },
    dateRow: { flexDirection: 'row', gap: 8 },
    dateField: { flex: 1 },
    clinicalField: { marginTop: 10, gap: 6 },
    input: {
      backgroundColor: colors.card,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.borderInput,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      fontFamily: fonts.sans,
      color: colors.text,
    },
    inputMultiline: { minHeight: 96, lineHeight: 22 },
    inputMultilineCompact: { minHeight: 80, lineHeight: 22 },
    allergenRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 4 },
    allergenName: {
      flex: 1,
      fontFamily: fonts.sansSemiBold,
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    allergenChange: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 13,
      fontWeight: '600',
      color: colors.accent,
    },
    catalogPickerBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 6,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.borderInput,
    },
    catalogPickerText: { flex: 1, fontFamily: fonts.sans, fontSize: 14, color: colors.textSecondary },
    uploadRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    uploadChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 6,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.borderInput,
    },
    uploadChipActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accentLight,
    },
    uploadChipText: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    uploadChipTextActive: { color: colors.accent },
    routeBubbles: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    routeBubble: {
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 6,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.borderInput,
    },
    routeBubbleActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent,
    },
    routeBubbleText: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    routeBubbleTextActive: { color: colors.card },
    ocrBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 6,
      backgroundColor: colors.accentLight,
      borderWidth: 1,
      borderColor: colors.accent,
    },
    ocrBtnCentered: {
      justifyContent: 'center',
      paddingVertical: 12,
    },
    ocrBtnText: { fontFamily: fonts.sansSemiBold, fontSize: 14, fontWeight: '600', color: colors.accent },
    ocrHint: {
      fontFamily: fonts.sans,
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 17,
      marginTop: 8,
    },
    empty: {
      fontFamily: fonts.sans,
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
      paddingVertical: 24,
    },
    hint: { fontFamily: fonts.sans, fontSize: 14, color: colors.textSecondary, lineHeight: 20 },
    stageRow: { fontFamily: fonts.sans, fontSize: 13, color: colors.textSecondary, lineHeight: 19 },
    reviewValue: { fontFamily: fonts.sansSemiBold, fontSize: 15, fontWeight: '600', color: colors.text },
    reminderList: { gap: 8, marginTop: 8 },
    reminderRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
    reminderField: { flex: 1, gap: 4 },
    reminderIconBtn: {
      width: 40,
      height: 44,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
    },
    reminderIconBtnSpacer: { width: 40, height: 44 },
    addReminderBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    addReminderText: {
      fontFamily: fonts.sansSemiBold,
      fontSize: 14,
      fontWeight: '600',
      color: colors.accent,
    },
    modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.35)' },
    modalSheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: radii.xl,
      borderTopRightRadius: radii.xl,
      paddingBottom: 24,
      maxHeight: '70%',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    modalTitle: { fontFamily: fonts.sans, fontSize: 15, fontWeight: '700', color: colors.text },
    modalCancel: { fontFamily: fonts.sans, fontSize: 15, color: colors.textSecondary },
    modalDone: { fontFamily: fonts.sans, fontSize: 15, fontWeight: '700', color: colors.accent },
    modalDoneDisabled: { opacity: 0.4 },
    parseInput: {
      flex: 1,
      margin: 16,
      backgroundColor: colors.card,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderInput,
      padding: 12,
      fontSize: 14,
      fontFamily: fonts.sans,
      color: colors.text,
      minHeight: 120,
    },
  });
}

export type CourseEditorStyles = ReturnType<typeof createCourseEditorStyles>;
