// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand/BrandInAction.tsx": () => import("../components/mockups/brand/BrandInAction.tsx"),
  "./components/mockups/brand/ColorsTypography.tsx": () => import("../components/mockups/brand/ColorsTypography.tsx"),
  "./components/mockups/brand/Guidelines.tsx": () => import("../components/mockups/brand/Guidelines.tsx"),
  "./components/mockups/brand/Logo.tsx": () => import("../components/mockups/brand/Logo.tsx")
};
